# Browser App
# Displays web search and reading activity from AI agents

id: browser
name: Browser
icon: icon.svg
description: Watch AI search the web and read pages

# Entity types this app displays
entities:
  - webpage
  - video

# Menu bar configuration
menus:
  - name: Browser
    items:
      - label: About Browser
        action: open_view
        view: about
  - name: History
    action: open_view
    view: history

views:
  # Search results view - shows webpage.search activities
  search:
    entity: webpage
    operation: search
    title: Browser
    toolbar:
      - component: url-bar
        props:
          mode: search
          value: "{{activity.request.params.query}}"
          source: "{{activity.connector}}"
          sourceIcon: "/plugins/{{activity.connector}}/icon.png"
    
    layout:
      - component: list
        data:
          source: activity
        item_component: items/search-result
        item_props:
          title: "{{title}}"
          url: "{{url}}"
          snippet: "{{snippet}}"
        footer:
          count: "{{activity.response.length}}"
          source: "{{activity.connector}}"
          duration: "{{activity.duration_ms}}"

  # Read view - shows webpage.read activities
  read:
    entity: webpage
    operation: read
    title: "{{activity.response.title}}"
    toolbar:
      - component: url-bar
        props:
          mode: url
          value: "{{activity.request.params.url}}"
          source: "{{activity.connector}}"
          sourceIcon: "/plugins/{{activity.connector}}/icon.png"
    
    layout:
      - component: layout/scroll-area
        children:
          - component: markdown
            props:
              content: "{{activity.response.content}}"
        footer:
          source: "{{activity.connector}}"
          duration: "{{activity.duration_ms}}"

  # Video view - shows video.get activities (YouTube, etc.)
  video:
    entity: video
    operation: get
    title: "{{activity.response.title}}"
    toolbar:
      - component: url-bar
        props:
          mode: url
          value: "{{activity.request.params.url}}"
          source: "{{activity.connector}}"
          sourceIcon: "/plugins/{{activity.connector}}/icon.png"
    
    layout:
      - component: layout/scroll-area
        children:
          - component: layout/stack
            props:
              direction: vertical
              gap: "16px"
            children:
              - component: media-header
                props:
                  thumbnail: "{{activity.response.thumbnail}}"
                  title: "{{activity.response.title}}"
                  creator: "{{activity.response.creator_name}}"
                  creatorUrl: "{{activity.response.creator_url}}"
                  duration: "{{activity.response.duration_ms}}"
              - component: text
                props:
                  content: "{{activity.response.description}}"
                  variant: body
        footer:
          source: "{{activity.connector}}"
          duration: "{{activity.duration_ms}}"

  # About view - shows app info
  about:
    title: About Browser
    layout:
      - component: layout/stack
        props:
          gap: 16
          align: center
          padding: 24
        children:
          - component: text
            props:
              content: "🌐"
              variant: title
              align: center
          - component: text
            props:
              content: Browser
              variant: title
              align: center
          - component: text
            props:
              content: Watch AI search the web and read pages
              variant: body
              align: center
          - component: text
            props:
              content: "Source: apps/browser/app.yaml"
              variant: caption
              align: center

  # History view - shows all browser activities (webpage + video)
  history:
    title: History
    layout:
      - component: layout/scroll-area
        children:
          - component: list
            data:
              source: activities
              entity: [webpage, video]
              limit: 100
            item_component: items/history-item
            item_props:
              operation: "{{operation}}"
              title: "{{response.title}}"
              query: "{{request.params.query}}"
              url: "{{request.params.url}}"
              connector: "{{connector}}"
              timestamp: "{{created_at}}"

default_view: search
