# Webpage Entity
# A web page with URL, title, and content

id: webpage
plural: webpages
name: Web Page
description: A web page with URL, title, and content

references:
  schema_org: https://schema.org/WebPage
  wikidata: Q36774  # web page

properties:
  url:
    type: string
    format: url
    required: true
    description: The page URL

  title:
    type: string
    description: Page title

  content:
    type: string
    description: Page content (markdown or text)

  snippet:
    type: string
    description: Short excerpt/description

  favicon:
    type: string
    format: url
    description: Site favicon URL

  published_at:
    type: datetime
    description: When the content was published

  fetched_at:
    type: datetime
    description: When we retrieved this content

operations: [search, read]

display:
  primary: title
  secondary: url
  description: snippet
  icon: globe

# Views for rendering webpage activities
# Note: Browser provides padding and status bar automatically
views:
  search:
    title: Browser
    layout:
      - component: list
        data:
          source: activity
        item_component: search-result
        item_props:
          title: "{{title}}"
          url: "{{url}}"
          snippet: "{{snippet}}"
          favicon: "{{favicon}}"

  read:
    title: "{{activity.response.title}}"
    layout:
      - component: markdown
        props:
          content: "{{activity.response.content}}"
