# Settings App
# System preferences and configuration for AgentOS

id: settings
name: Settings
icon: icon.svg
description: Configure AgentOS preferences, plugins, and credentials

# What this app manages (shown in MCP tool description)
manages:
  - all plugins
  - all credentials
  - system settings

# Menu bar configuration
menus:
  - name: Settings
    items:
      - label: About Settings
        action: open_view
        view: about
  - name: File
    items:
      - label: Export Settings...
        action: export_settings
      - label: Import Settings...
        action: import_settings
  - name: Plugins
    items:
      - label: Reload All
        action: reload_plugins
      - separator: true
      - label: View Sources
        action: open_view
        view: sources

views:
  # Main tabbed settings panel
  # Uses data-driven components that fetch from /api/settings
  main:
    title: Settings
    layout:
      - component: tabs
        props:
          tabs:
            - id: appearance
              label: Appearance
            - id: features
              label: Features
            - id: privacy
              label: Privacy
            - id: plugins
              label: Plugins
            - id: handlers
              label: Handlers
            - id: accounts
              label: Accounts
            - id: about
              label: About
          default: appearance
          activeTab: "{{params.tab}}"
        slots:
          appearance:
            component: layout/scroll-area
            children:
              - component: layout/stack
                props:
                  gap: 16
                children:
                  - component: text
                    props:
                      content: Wallpaper
                      variant: title
                  - component: wallpaper-picker

          features:
            component: layout/scroll-area
            children:
              - component: layout/stack
                props:
                  gap: 16
                children:
                  - component: settings-panel
                    props:
                      category: features

          privacy:
            component: layout/scroll-area
            children:
              - component: layout/stack
                props:
                  gap: 16
                children:
                  - component: settings-panel
                    props:
                      category: privacy

          plugins:
            component: layout/scroll-area
            children:
              - component: layout/stack
                props:
                  gap: 16
                children:
                  - component: text
                    props:
                      content: Installed Plugins
                      variant: title
                  - component: plugin-list

          handlers:
            component: layout/scroll-area
            children:
              - component: layout/stack
                props:
                  gap: 16
                children:
                  - component: settings-panel
                    props:
                      category: handlers

          accounts:
            component: layout/scroll-area
            children:
              - component: layout/stack
                props:
                  gap: 16
                children:
                  - component: text
                    props:
                      content: Configured Accounts
                      variant: title
                  - component: credential-list

          about:
            component: layout/scroll-area
            children:
              - component: layout/stack
                props:
                  gap: 16
                children:
                  - component: about-panel

  # Standalone about view (accessible from menu)
  about:
    title: About AgentOS
    layout:
      - component: layout/scroll-area
        children:
          - component: layout/stack
            props:
              gap: 16
              padding: 16
            children:
              - component: about-panel

  # Plugin sources view
  sources:
    title: Plugin Sources
    layout:
      - component: layout/scroll-area
        children:
          - component: layout/stack
            props:
              gap: 16
              padding: 16
            children:
              - component: text
                props:
                  content: Plugin Sources
                  variant: title
              - component: settings-panel
                props:
                  category: paths

default_view: main
