# Browser App
# Displays web search and reading activity from AI agents

id: browser
name: Browser
icon: globe
description: Watch AI search the web and read pages

# What activities this app displays
displays:
  - web_search
  - web_read

views:
  # Search results view - shows web_search activity
  search:
    title: Browser
    toolbar:
      - component: url-bar
        props:
          mode: search
          query: "{{activity.request.query}}"
          loading: "{{activity.pending}}"
          source: "{{activity.connector}}"
    
    layout:
      - component: list
        data:
          source: activity
          filter: web_search
        item_component: items/search-result
        item_props:
          title: "{{title}}"
          url: "{{url}}"
          snippet: "{{snippet}}"
        footer:
          count: "{{activity.response.length}}"
          source: "{{activity.connector}}"
          duration: "{{activity.duration_ms}}"

  # Read view - shows web_read activity
  read:
    title: "{{activity.response.title}}"
    toolbar:
      - component: url-bar
        props:
          mode: url
          url: "{{activity.request.url}}"
          loading: "{{activity.pending}}"
          source: "{{activity.connector}}"
    
    layout:
      - component: scroll-area
        children:
          - component: markdown
            content: "{{activity.response.content}}"
        footer:
          source: "{{activity.connector}}"
          duration: "{{activity.duration_ms}}"

default_view: search
